In [1]:
import numpy as np

# Creating Numpy Arrays from Python Lists

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [4]:
a1 = np.array([1,2,3,4])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3], 
               [4,5,6]])

In [8]:
type(a2)

numpy.ndarray

In [9]:
a2.shape

(2, 3)

In [10]:
a2.ndim

2

In [12]:
a2.dtype

dtype('int32')

In [13]:
a2.size

6

## Creating Numpy Arrays from Scratch
### zeros, ones, full, arange, linspace

In [14]:
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
np.ones([3,5], dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.arange(0,20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [14]:
np.full((3,5), 5.4)

array([[5.4, 5.4, 5.4, 5.4, 5.4],
       [5.4, 5.4, 5.4, 5.4, 5.4],
       [5.4, 5.4, 5.4, 5.4, 5.4]])

In [16]:
np.linspace(0,3, 5)

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

### random


In [21]:
##### seed for reproducibility
np.random.random((4,4))

array([[0.77662146, 0.8197019 , 0.48632169, 0.33727332],
       [0.89844049, 0.74733489, 0.68669225, 0.60832037],
       [0.96727551, 0.06692911, 0.67364319, 0.89215341],
       [0.67998508, 0.6511952 , 0.16650021, 0.95808811]])

In [20]:
np.random.rand(4,4)

array([[0.52906438, 0.9182056 , 0.98352529, 0.86196743],
       [0.88481093, 0.77727408, 0.32246713, 0.17004893],
       [0.6118249 , 0.21047885, 0.69378208, 0.54595436],
       [0.72095732, 0.43857125, 0.17534607, 0.33513891]])

In [21]:
np.random.normal(0,1, (3,3))

array([[-0.06171847,  1.22032485, -1.08550469],
       [ 0.97048727,  1.08175761,  0.15334809],
       [-0.7029806 ,  0.65510852,  0.91863343]])

In [22]:
np.random.randint(0,10, (4,5))

array([[6, 0, 3, 0, 2],
       [7, 6, 0, 1, 0],
       [0, 0, 9, 3, 3],
       [2, 7, 2, 8, 6]])

## Array Indexing & Slicing
### One-dimensional subarray

In [25]:
x1 = np.random.randint(20, size = 6)

In [26]:
x1

array([ 7,  2, 15,  3,  2, 18])

In [29]:
x1[4], x1[0]

(2, 7)

#### Multi-dimensional array

In [30]:
x2 = np.random.randint(10, size = (3,4))

In [31]:
x2

array([[3, 1, 3, 7],
       [2, 2, 4, 8],
       [7, 4, 2, 6]])

In [32]:
x2[1,2]

4

In [33]:
x2[1,2] = 6

In [34]:
x2

array([[3, 1, 3, 7],
       [2, 2, 6, 8],
       [7, 4, 2, 6]])

##### Slincing
x[start:stop:step]

In [28]:
x1

array([ 7,  2, 15,  3,  2, 18])

In [32]:
x1[0:3]

array([ 5, 11, 18])

In [33]:
x1[2:4]

array([18, 11])

In [27]:
x1[::3]

array([7, 3])

In [35]:
x2

array([[3, 1, 3, 7],
       [2, 2, 6, 8],
       [7, 4, 2, 6]])

In [40]:
x2[1:3,1:4]

array([[2, 6, 8],
       [4, 2, 6]])

In [37]:
x2[:,:2]

array([[8, 3],
       [2, 6],
       [9, 5]])

#### Reshaping of Arrays & Transpose

In [41]:
grid = np.arange(1,10)
grid.shape

(9,)

In [51]:
grid.reshape((3,3))

ValueError: cannot reshape array of size 6 into shape (3,3)

In [43]:
x = np.array([1,2,3])

In [44]:
x.shape

(3,)

In [45]:
x.reshape((1,3)).shape

(1, 3)

In [46]:
x = np.array([[1.,2.],[3.,4.]])

In [47]:
x

array([[1., 2.],
       [3., 4.]])

In [48]:
x.T

array([[1., 3.],
       [2., 4.]])

#### Array Concatenation and Splitting

In [49]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [47]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [50]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [52]:
x = np.array([1,2,3])
grid = np.array([[9,8,7], [6,5,4]])

In [53]:
np.vstack((x, grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [54]:
y = np.array([[99], [99]])
np.hstack((y, grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

##### Splitting of arrays

In [55]:
x = np.array([1,2,3,99,69,3,2,1])

In [56]:
x, x2, x3 = np.split(x, [3,5])

In [57]:
x1

array([ 5, 11, 18, 11, 16, 15])

### Broadcasting and Vectorized operations

In [58]:
a = np.arange(3)

In [59]:
a

array([0, 1, 2])

In [60]:
a + 5

array([5, 6, 7])

In [61]:
b = np.ones((3,3))

In [62]:
a.shape, b.shape

((3,), (3, 3))

In [63]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [64]:
a * b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [65]:
c = np.arange(3).reshape((3,1))

In [66]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

###### Manipulating & Comparing Arrays

In [67]:
list_number = [1,2,3]

In [68]:
ll = np.array(list_number)

In [69]:
ll

array([1, 2, 3])

In [70]:
sum(ll)

6

In [71]:
np.sum(ll)

6

In [73]:
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [74]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

666 µs ± 2.43 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
6.4 µs ± 70.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [75]:
np.mean(massive_array)

0.49785537711237693

In [76]:
np.max(massive_array)

0.9996253110918485

In [77]:
dog_height = [600, 470, 170, 430, 300]
dog_height = np.array(dog_height)
np.std(dog_height)

147.32277488562318

In [78]:
np.var(dog_height)

21704.0

In [79]:
np.sqrt(np.var(dog_height))

147.32277488562318

### Sorting Arrays 

In [80]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [81]:
np.argsort(x)

array([1, 0, 3, 2, 4], dtype=int64)

In [82]:
np.random.seed(42)
MatA = np.random.randint(0,10, size = (4,6))

In [83]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [84]:
np.sort(MatA, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [85]:
np.sort(MatA, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

#### Dai so tuyen tinh

In [55]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [56]:
B = np.array([[6,5], [4,3], [2,1]])

In [60]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [58]:
A@B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [61]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size = (5,3))

In [62]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [63]:
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tues", "Wed", "Thus", "Fri"],
                    columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [64]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thus              4              6             12
Fri               1              6              7

In [65]:
prices = np.array([10,8,12])

In [66]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Price"], 
columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [67]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [68]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [110]:
total_prices = weekly_sales.dot(butter_prices.T)

In [111]:
total_prices

Price
Mon     240
Tues    138
Wed     458
Thus    232
Fri     142

In [113]:
weekly_sales["Total Price"] = total_prices
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total Price
Mon              12             15              0          240
Tues              3              3              7          138
Wed               9             19             18          458
Thus              4              6             12          232
Fri               1              6              7          142